export const SKILL_CATEGORIES = [
  { id: 'orchestration', number: '01', label: '规划与验证', summary: '决定使用哪些专家能力，并用可重复证据验收结果。' },
  { id: 'camera-motion', number: '02', label: '镜头与运动', summary: '控制场景如何被观看，以及对象如何按语义运动。' },
  { id: 'generation', number: '03', label: '场景与资产', summary: '生成几何、建筑、植被、行星和统一的表面结构。' },
  { id: 'environment', number: '04', label: '环境与特效', summary: '构建水体、天气、大气、云、太空和实时视觉特效。' },
  { id: 'image', number: '05', label: '光照与画质', summary: '组织阴影、环境遮蔽、泛光、曝光和最终图像管线。' },
];

export const THREEJS_SKILLS = [
  {
    id: 'threejs-skill-router', short: 'ROUTER', category: 'orchestration', role: '编排',
    title: 'Three.js Skill 路由器', summary: '把宽泛视觉目标拆成最小且必要的专家 Skill 组合。',
    when: '新视觉体验、画面重写、参考图还原，或需求同时跨越几何、材质、天气和后期时。',
    inputs: ['视觉目标', '尺度与镜头', '运动方式', '帧预算'], outputs: ['Skill 组合', '执行顺序', '验收门槛'],
    rules: ['只加载真正改变画面的 Skill', '先定义视觉契约，再写场景', '必须保留无后期基线和调试视图'],
    examples: [], related: ['threejs-camera-direction', 'threejs-image-pipeline', 'threejs-visual-validation'],
  },
  {
    id: 'threejs-visual-validation', short: 'VALIDATE', category: 'orchestration', role: '验证',
    title: '高级图形验证', summary: '用固定镜头、种子扫描、诊断通道和 GPU 预算验证图形机制。',
    when: '高级效果完成后，需要证明它不依赖一张英雄截图、不因随机种子或镜头距离崩坏时。',
    inputs: ['固定种子', '固定镜头', '质量档', '性能预算'], outputs: ['无后期截图', '诊断拼图', '时序与性能证据'],
    rules: ['冻结可重复输入', '检查近中远镜头', '记录 GPU 与渲染目标预算'],
    examples: [], related: ['threejs-skill-router', 'threejs-image-pipeline'],
  },
  {
    id: 'threejs-camera-direction', short: 'CAMERA', category: 'camera-motion', role: '观看',
    title: '镜头导演系统', summary: '构建跟随、环绕、侧视、电影镜头、切换和大世界相机。',
    when: '镜头决定空间感、需要模式切换、跟随惯性、行星表面方向或浮动原点时。',
    inputs: ['主体尺寸', '镜头占比', '焦距与裁剪面', '上方向与目标'], outputs: ['镜头 Rig', '切换规则', '输入与恢复机制'],
    rules: ['偏移由主体尺度决定', '位置 lerp、方向 slerp', '切换期间只保留一个插值阶段'],
    examples: [], related: ['threejs-procedural-animation', 'threejs-visual-validation'],
  },
  {
    id: 'threejs-procedural-animation', short: 'MOTION', category: 'camera-motion', role: '运动',
    title: '程序化动画', summary: '用阶段、坐标系、解析运动和弹簧构建可重复的复杂动画。',
    when: '发射、分级、旋转对接、机械运动、碎片脱落或帧率无关的响应运动时。',
    inputs: ['时间阶段', '运动坐标系', '目标姿态', '速度与弹簧参数'], outputs: ['对象时间线', '对接与分级', '可重播运动状态'],
    rules: ['按语义状态而非无关曲线动画', '使用秒和 deltaSeconds', '重放时重置全部状态'],
    examples: [], related: ['threejs-camera-direction', 'threejs-procedural-vfx'],
  },
  {
    id: 'threejs-procedural-fields', short: 'FIELDS', category: 'generation', role: '基础',
    title: '程序化场', summary: '建立共享标量场和向量场，让形状、材质和法线来自同一原因。',
    when: '地形、行星、磨损、云、水等多个通道必须保持结构一致时。',
    inputs: ['稳定坐标', '宏观/中观频段', '因果遮罩', '过滤尺度'], outputs: ['高度场', '区域/坡度/侵蚀场', '调试通道'],
    rules: ['先定义物理或风格字段，再叠加噪声', '同一场驱动颜色、粗糙度和法线', '高频必须按距离过滤'],
    examples: [], related: ['threejs-procedural-materials', 'threejs-procedural-planets'],
  },
  {
    id: 'threejs-procedural-materials', short: 'MATERIAL', category: 'generation', role: '生成',
    title: '程序化 PBR 材质', summary: '从表面身份与成因构建土壤、苔藓、湿地、熔岩和行星材质。',
    when: '模型表面塑料感强，或颜色、粗糙度、法线、湿度需要因果一致时。',
    inputs: ['稳定坐标', '材质身份权重', '湿度/高度等原因场', '纹理尺度'], outputs: ['PBR 通道', '微表面与过滤', '材质诊断'],
    rules: ['各 PBR 通道不能各用一套无关噪声', '必须处理远距离高频闪烁', '后期不能掩盖不稳定高光'],
    examples: ['hybrid-soil-moss-surface', 'lava-flow-surface'], related: ['threejs-procedural-fields', 'threejs-parallax-occlusion-mapping'],
  },
  {
    id: 'threejs-parallax-occlusion-mapping', short: 'RELIEF', category: 'generation', role: '增强',
    title: '视差遮挡与浮雕', summary: '用高度场射线步进生成凹凸交点、轮廓裁切、自阴影和浮雕深度。',
    when: '砖墙、甲板、岩石等近景表面需要真实厚度感，但不适合增加大量几何时。',
    inputs: ['高度图', '切线空间', '视线与光线', '层数和轮廓范围'], outputs: ['浮雕 UV', '高度法线', '自阴影与轮廓'],
    rules: ['交点、覆盖、法线、阴影是一套系统', '曲面不能使用平面轮廓假设', '提供高度与阴影诊断'],
    examples: ['silhouette-relief'], related: ['threejs-procedural-materials', 'threejs-procedural-geometry'],
  },
  {
    id: 'threejs-procedural-geometry', short: 'GEOMETRY', category: 'generation', role: '生成',
    title: '程序化几何', summary: '从语义尺寸和局部坐标系编译车辆、机械、框架及复杂网格。',
    when: '需要由代码生成可近距离检查的硬表面模型、扫掠、放样和完整装配体时。',
    inputs: ['尺寸契约', '中心线/截面/边界', '材质槽', 'UV 密度'], outputs: ['BufferGeometry', '法线与 UV', '复杂度诊断'],
    rules: ['三角形发射是最后一步', '缝、硬边和材质所有权必须明确', '检查绕序、退化面和封闭体积'],
    examples: ['formula-one-race-car', 'porcelain-brass-submarine', 'sculpted-gallery-frame', 'sport-motorcycle'], related: ['threejs-procedural-architecture', 'threejs-procedural-vegetation'],
  },
  {
    id: 'threejs-procedural-vegetation', short: 'VEGETATION', category: 'generation', role: '生成',
    title: '程序化植被', summary: '生成树木、草地、藤蔓、根系、叶片以及锚定根部的风动。',
    when: '森林、乡村、草原或建筑表面需要大量可控、可重复的植被时。',
    inputs: ['物种层级表', '生长种子', '地形/表面', '风场'], outputs: ['枝干与叶片', '草地/藤蔓实例', 'LOD 与风动'],
    rules: ['植物是生长层级，不是随机圆柱', '叶片和草根必须保持锚定', '不同种子不能改变物种身份'],
    examples: ['gpu-computed-grass', 'procedural-surface-ivy', 'structured-ash-growth', 'stylized-meadow-grass'], related: ['threejs-procedural-geometry', 'threejs-procedural-fields'],
  },
  {
    id: 'threejs-procedural-architecture', short: 'ARCH', category: 'generation', role: '生成',
    title: '程序化建筑', summary: '从体块语法、外露边分析和立面模块编译建筑与城市资产。',
    when: '城市、园区或村落需要可变体、可检查、受真实尺寸约束的建筑生成器时。',
    inputs: ['建筑设置', '体块语法', '立面和屋顶模块', '材质槽'], outputs: ['建筑计划', '立面/屋顶放置', '合并几何'],
    rules: ['先生成可检查计划，再生成三角形', '隐藏内表面不能装饰', '随机只能在有效设计中选择'],
    examples: ['procedural-financial-tower'], related: ['threejs-procedural-geometry', 'threejs-shadow-systems'],
  },
  {
    id: 'threejs-procedural-planets', short: 'PLANETS', category: 'generation', role: '生成',
    title: '程序化行星', summary: '构建可从轨道接近地表观察的山脉、陨石坑、海岸和生物群落。',
    when: '制作火星、地球、气态巨行星或需要轨道到近景连续尺度的球形地形时。',
    inputs: ['行星半径', '海平面', '地质字段', '相机高度'], outputs: ['球形位移', '地貌与生物群落', '高度 LOD'],
    rules: ['地形、法线和材质必须共享地质原因', '陨石坑需要底、壁、缘', '宏观轮廓不能随距离消失'],
    examples: ['procedural-planet-surface'], related: ['threejs-procedural-fields', 'threejs-atmosphere-aerial-perspective'],
  },
  {
    id: 'threejs-spectral-ocean', short: 'OCEAN', category: 'environment', role: '生成',
    title: '频谱海洋', summary: '用方向波谱、FFT 级联、导数和 Jacobian 泡沫构建大尺度海洋。',
    when: '远洋、船舶或水上/水下镜头需要真实海况和多波长尺度时。',
    inputs: ['海况波谱', '风向风速', '确定性高斯种子', 'FFT 网格'], outputs: ['多级联位移', '导数与法线', '白浪/泡沫与水下光学'],
    rules: ['FFT 必须有解析测试', '法线来自变换后的导数', '泡沫必须有持续状态而非每帧重算'],
    examples: ['hybrid-clear-water-ocean', 'spectral-cascade-ocean', 'stylized-above-below-ocean', 'submerged-snell-ocean'], related: ['threejs-water-optics', 'threejs-atmosphere-aerial-perspective', 'threejs-visual-validation'],
  },
  {
    id: 'threejs-water-optics', short: 'WATER', category: 'environment', role: '生成',
    title: '局部水体光学', summary: '构建解析波、泳池高度场、局部涟漪、焦散、折射和吸收。',
    when: '泳池、河道、积水或有边界水体需要交互波纹和真实光学时。',
    inputs: ['波段/高度场', '场景颜色与深度', '物体交互', '水体边界'], outputs: ['位移与共享法线', '反射/折射/吸收', '焦散与泡沫'],
    rules: ['位移和法线必须一致', 'Fresnel 不能用固定透明度替代', '有边界水体不能假装成开放海洋'],
    examples: ['analytic-wave-optics', 'interactive-pool-volume'], related: ['threejs-spectral-ocean', 'threejs-precipitation-surfaces'],
  },
  {
    id: 'threejs-precipitation-surfaces', short: 'WEATHER', category: 'environment', role: '生成',
    title: '降水与地表联动', summary: '把雨雪事件与积雪、湿地、积水、涟漪和飞溅统一起来。',
    when: '暴雨城市、雪景或灾害场景不能只显示悬空粒子，地面也必须响应天气时。',
    inputs: ['天气进度', '风向与强度', '地表方向/遮罩', '降水密度'], outputs: ['雨雪体积', '湿润/积雪遮罩', '涟漪与飞溅'],
    rules: ['降水和表面必须共享时间与风', '雪只覆盖朝上表面', '保留示例代码的许可证边界'],
    examples: ['snow-accumulation', 'wet-puddle-rain'], related: ['threejs-water-optics', 'threejs-temporal-surfaces'],
  },
  {
    id: 'threejs-atmosphere-aerial-perspective', short: 'ATMOS', category: 'environment', role: '生成',
    title: '大气与空气透视', summary: '用统一散射模型生成天空、太阳透射和物体远景入射光。',
    when: '大型户外、地面到太空过渡或远近尺度需要 Rayleigh/Mie 层次时。',
    inputs: ['行星半径', '密度剖面', '散射系数', '太阳方向'], outputs: ['天空辐射', '太阳颜色', '深度空气透视'],
    rules: ['天空和地表雾必须共享参数', '不能用透明球代替大气', '曝光不能掩盖错误辐射尺度'],
    examples: ['lut-aerial-perspective'], related: ['threejs-procedural-planets', 'threejs-volumetric-clouds'],
  },
  {
    id: 'threejs-volumetric-clouds', short: 'CLOUDS', category: 'environment', role: '生成',
    title: '体积云', summary: '通过天气场、有限体积射线步进、光照和时间重建生成云层。',
    when: '天空、飞行或天气系统需要可穿越、带银边和云影的动态云时。',
    inputs: ['天气图', '云层高度', '形状/细节场', '风与质量档'], outputs: ['体积云辐射', '时间重建', '低成本云影'],
    rules: ['密度不能只是 fBM(position)', '只步进有界占用区间', '历史必须在遮挡变化时拒绝'],
    examples: ['weather-volume-clouds'], related: ['threejs-atmosphere-aerial-perspective', 'threejs-image-pipeline'],
  },
  {
    id: 'threejs-raymarched-space-effects', short: 'SPACE FX', category: 'environment', role: '生成',
    title: '光线步进太空现象', summary: '用受控数值积分生成黑洞透镜、吸积盘、虫洞和弯曲光线。',
    when: '太空英雄镜头需要真正的逐像素弯曲积分，而不是二维 UV 扭曲时。',
    inputs: ['效果坐标系', '弯曲模型', '积分域', '终止条件'], outputs: ['弯曲光线路径', '吸积辐射', '程序化深空背景'],
    rules: ['限制迭代并提前终止', '薄结构使用连续穿越测试', '积分器与着色分离'],
    examples: ['curved-ray-accretion-volume', 'schwarzschild-geodesic-black-hole'], related: ['threejs-procedural-vfx', 'threejs-bloom'],
  },
  {
    id: 'threejs-procedural-vfx', short: 'VFX', category: 'environment', role: '生成',
    title: '程序化实时 VFX', summary: '构建极光、体积火焰烟雾、再入等离子、火花、碎片和全息效果。',
    when: '游戏技能、科幻事件、火焰烟雾或 HDR 发光特效需要完整生命周期和诊断时。',
    inputs: ['事件包络', '运动/流场', '几何或体素表示', '生命周期'], outputs: ['粒子/体积/壳层效果', '实例池', 'HDR 发光贡献'],
    rules: ['每一层必须承担轮廓、运动、照明或残留角色', '实例必须池化', 'Bloom 不能成为效果唯一形状'],
    examples: ['holographic-shape-transition', 'raymarched-aurora-curtains', 'reentry-plasma', 'volumetric-fluid-fire'], related: ['threejs-procedural-animation', 'threejs-bloom'],
  },
  {
    id: 'threejs-temporal-surfaces', short: 'TEMPORAL', category: 'environment', role: '生成',
    title: '时间累积表面', summary: '构建玻璃雨滴、结霜、触摸擦除、折射和屏幕空间历史状态。',
    when: '车窗、玻璃、屏幕或视线对齐表面需要持续历史和光学变化时。',
    inputs: ['上一帧历史', '触摸/覆盖输入', '场景颜色', '模糊与折射参数'], outputs: ['Ping-pong 状态', '结霜/雨滴遮罩', '折射与模糊'],
    rules: ['区分持久状态、解析状态和场景颜色', '衰减必须帧率无关', '明确 resize/reset 行为'],
    examples: ['refractive-window-rain', 'touch-history-frost'], related: ['threejs-precipitation-surfaces', 'threejs-image-pipeline'],
  },
  {
    id: 'threejs-shadow-systems', short: 'SHADOWS', category: 'image', role: '增强',
    title: '大世界阴影系统', summary: '用级联或缓存 Clipmap 构建移动镜头下稳定、可预算的方向光阴影。',
    when: '大型地形、城市或移动相机让单张阴影贴图闪烁、模糊或覆盖不足时。',
    inputs: ['接收区域', '光空间层级', '纹素尺寸', '更新预算'], outputs: ['多级阴影图', '稳定切换', '局部失效更新'],
    rules: ['每级中心吸附到纹素网格', '粗级不能永久冻结动态物体', 'Bias 随世界纹素尺寸缩放'],
    examples: [], related: ['threejs-screen-space-ambient-occlusion', 'threejs-procedural-architecture'],
  },
  {
    id: 'threejs-screen-space-ambient-occlusion', short: 'GTAO', category: 'image', role: '增强',
    title: '屏幕空间环境遮蔽', summary: '用 GTAO、弯曲法线和双边重建增强接触与间接光遮蔽。',
    when: '模型与地面缺少接触感、角落过亮，同时已有可靠深度和法线缓冲时。',
    inputs: ['线性深度', '视空间法线', '世界半径', '采样方向'], outputs: ['AO', '弯曲法线', '全分辨率重建'],
    rules: ['只调制间接光，不压暗直射光和发光', '半径不能只用像素表示', '深度边缘不能被模糊穿透'],
    examples: [], related: ['threejs-shadow-systems', 'threejs-image-pipeline'],
  },
  {
    id: 'threejs-bloom', short: 'BLOOM', category: 'image', role: '增强',
    title: 'HDR Bloom', summary: '从场景相对 HDR 亮度中提取并组合可控、可选择的泛光。',
    when: '霓虹、魔法、火焰或科幻灯光需要明亮能量扩散，但主体无 Bloom 仍可读时。',
    inputs: ['HDR 亮度', '阈值', '半径', '选择性贡献'], outputs: ['Bloom 贡献', '多尺度模糊', '效果隔离视图'],
    rules: ['先确定曝光和发光亮度', 'Bloom 必须在色调映射前', '选择性材质替换必须可靠恢复'],
    examples: [], related: ['threejs-exposure-color-grading', 'threejs-image-pipeline'],
  },
  {
    id: 'threejs-exposure-color-grading', short: 'GRADE', category: 'image', role: '增强',
    title: '曝光与色彩分级', summary: '通过亮度测量、非对称适应、单次色调映射和 3D LUT 完成输出。',
    when: '场景跨越室内外、昼夜或 HDR 强光，需要稳定曝光和统一电影色彩时。',
    inputs: ['HDR 场景', '亮度测量', '适应速度', 'LUT'], outputs: ['自适应曝光', '色调映射', '最终色彩'],
    rules: ['曝光不能修复错误光照比例', '明适应和暗适应速度不同', '只能进行一次输出编码'],
    examples: [], related: ['threejs-bloom', 'threejs-image-pipeline'],
  },
  {
    id: 'threejs-image-pipeline', short: 'PIPELINE', category: 'image', role: '编排',
    title: '最终图像管线', summary: '协调深度、法线、AO、Bloom、曝光、色调映射和调色的信号所有权。',
    when: '两个以上屏幕空间效果必须共享缓冲、分辨率和执行顺序时。',
    inputs: ['HDR 颜色', '深度/法线/反照率', '各效果贡献', '历史缓冲'], outputs: ['有序 Pass 图', '共享缓冲契约', '效果开关与诊断'],
    rules: ['色调映射只能一次', '低分辨率效果必须深度/法线感知上采样', '不要默认加载全部后期'],
    examples: [], related: ['threejs-screen-space-ambient-occlusion', 'threejs-bloom', 'threejs-exposure-color-grading'],
  },
];

export const SKILL_RECIPES = [
  {
    id: 'ocean-world', label: '真实海洋', outcome: '从确定性波谱生成可跨越水上/水下镜头的多尺度海洋。',
    skills: ['threejs-skill-router', 'threejs-camera-direction', 'threejs-spectral-ocean', 'threejs-atmosphere-aerial-perspective', 'threejs-volumetric-clouds', 'threejs-bloom', 'threejs-exposure-color-grading', 'threejs-image-pipeline', 'threejs-visual-validation'],
  },
  {
    id: 'storm-village', label: '暴雨乡村', outcome: '把建筑、植被、湿材质、降雨、积水与镜头组合成完整天气空间。',
    skills: ['threejs-skill-router', 'threejs-camera-direction', 'threejs-procedural-architecture', 'threejs-procedural-vegetation', 'threejs-procedural-materials', 'threejs-precipitation-surfaces', 'threejs-water-optics', 'threejs-shadow-systems', 'threejs-exposure-color-grading', 'threejs-visual-validation'],
  },
  {
    id: 'mars-mission', label: '火星任务', outcome: '生成从轨道到地表都成立的火星、稀薄大气、探测器与镜头。',
    skills: ['threejs-skill-router', 'threejs-procedural-fields', 'threejs-procedural-planets', 'threejs-atmosphere-aerial-perspective', 'threejs-procedural-geometry', 'threejs-procedural-animation', 'threejs-camera-direction', 'threejs-shadow-systems', 'threejs-exposure-color-grading', 'threejs-visual-validation'],
  },
  {
    id: 'sci-fi-event', label: '科幻事件', outcome: '把机械运动、等离子、火花、全息和 HDR 发光组织成一个可重播事件。',
    skills: ['threejs-skill-router', 'threejs-procedural-geometry', 'threejs-procedural-animation', 'threejs-procedural-vfx', 'threejs-bloom', 'threejs-exposure-color-grading', 'threejs-image-pipeline', 'threejs-visual-validation'],
  },
  {
    id: 'procedural-city', label: '程序化城市', outcome: '从建筑计划生成城市体块，并用稳定阴影、AO 和调色完成可读空间。',
    skills: ['threejs-skill-router', 'threejs-procedural-architecture', 'threejs-procedural-materials', 'threejs-camera-direction', 'threejs-shadow-systems', 'threejs-screen-space-ambient-occlusion', 'threejs-exposure-color-grading', 'threejs-image-pipeline', 'threejs-visual-validation'],
  },
  {
    id: 'wet-window', label: '雨夜车窗', outcome: '在屏幕空间积累雨滴和结霜，并折射、模糊后方真实场景。',
    skills: ['threejs-skill-router', 'threejs-temporal-surfaces', 'threejs-exposure-color-grading', 'threejs-image-pipeline', 'threejs-visual-validation'],
  },
];

export const SCENE_DEMOS = [
  {
    id: 'planet-skill-lab', group: 'direct', number: '01', title: '程序化行星控制实验', href: './skill-lab.html',
    status: '直接本地 Skill 实验', summary: '从普通材质球开始，逐层查看高度、陆海、气候、生物群落、最终材质和法线诊断。',
    truth: '运行代码直接导入项目内 .codex/skills/threejs-procedural-planets 随附实现。',
    boundary: '本实验验证程序化行星表面；页面布局、步骤控制和讲解由产品层实现。',
    skills: [
      { id: 'threejs-procedural-planets', relation: '直接实现', role: '共享地形场、陆海、气候、群落、材质和诊断视图' },
    ],
  },
  {
    id: 'polar-night', group: 'direct', number: '02', title: '极夜星空与体积极光', href: './?scene=polar-night',
    status: '采用上游示例实现', summary: '把背景场、星点、闪烁、有限体积极光和最终输出拆成五个可观察阶段。',
    truth: '极光核心采用仓库 procedural-vfx 的 raymarched aurora 实现，产品层负责阶段控制与页面组织。',
    boundary: '星空组合、讲解界面和交互不属于 Skill 自带的一键场景。',
    skills: [
      { id: 'threejs-procedural-vfx', relation: '直接实现', role: '有限体积极光、噪声密度与射线积分' },
      { id: 'threejs-exposure-color-grading', relation: '对应机制', role: '曝光、伽马与最终颜色输出顺序' },
      { id: 'threejs-visual-validation', relation: '验收方法', role: '分层开关与可复现过程观察' },
    ],
  },
  {
    id: 'deep-space', group: 'composed', number: '03', title: '全屏深空星海', href: './?scene=deep-space',
    status: '按机制组合', summary: '使用方向哈希星点、不同深度层和低频星云带组成没有地平线的深空环境。',
    truth: '这是产品层编写的 Three.js/Shader 场景，不是 raymarched-space-effects 提供的现成示例。',
    boundary: '黑洞、虫洞和弯曲光线才属于 raymarched-space-effects；普通星空不应错误归给它。',
    skills: [
      { id: 'threejs-procedural-fields', relation: '相关机制', role: '可复现方向场、分层密度与噪声结构' },
      { id: 'threejs-procedural-vfx', relation: '相关机制', role: '发光星点与星云视觉层' },
      { id: 'threejs-exposure-color-grading', relation: '输出机制', role: '控制深空暗部和亮星的最终动态范围' },
    ],
  },
  {
    id: 'solar-system', group: 'composed', number: '04', title: '可拖动太阳系', href: './?scene=solar-system',
    status: 'Three.js 产品组合', summary: '太阳、六颗行星、月球、轨道和小行星带在同一透视空间中运动。',
    truth: '行星模型由基础 Three.js 球体和材质编写；没有直接使用程序化行星 Skill。',
    boundary: 'Skill 负责镜头与运动方法，具体天体数据、轨道参数和场景内容由产品代码负责。',
    skills: [
      { id: 'threejs-camera-direction', relation: '能力映射', role: '环绕观察、缩放边界和空间构图' },
      { id: 'threejs-procedural-animation', relation: '能力映射', role: '轨道相位、自转与层级运动' },
    ],
  },
  {
    id: 'storm-city', group: 'composed', number: '05', title: '暴雨城市', href: './?scene=storm-city',
    status: '按 Skill 机制组合', summary: '逐层加入城市体块、湿路面、积水、雨线和闪电，观察天气怎样改变空间。',
    truth: '场景由产品层代码实现，采用了降水—地表联动和程序化建筑的核心组织方式。',
    boundary: '它不是从 Skill 目录直接加载的城市模板；建筑布局和闪电节奏是当前产品实现。',
    skills: [
      { id: 'threejs-precipitation-surfaces', relation: '主机制', role: '雨线、湿地面、积水和涟漪联动' },
      { id: 'threejs-procedural-architecture', relation: '主机制', role: '城市体块、建筑重复与空间层次' },
      { id: 'threejs-camera-direction', relation: '辅助能力', role: '街道尺度下的观察和拖动视角' },
      { id: 'threejs-exposure-color-grading', relation: '辅助能力', role: '暴雨暗部、闪电高光和输出对比' },
    ],
  },
  {
    id: 'mars-exploration', group: 'composed', number: '06', title: '火星探测', href: './?scene=mars-exploration',
    status: '按 Skill 机制组合', summary: '把火星球体、尘埃天空、地形、陨石坑、探测车、车辙和轨道线放进同一任务视角。',
    truth: '当前实现是产品层的轻量近似，用来证明能力组合，不是直接运行程序化行星完整示例。',
    boundary: '任务叙事、探测路线和探测车结构由产品代码决定。',
    skills: [
      { id: 'threejs-procedural-planets', relation: '主机制', role: '火星身份、地形层次和陨石坑方向' },
      { id: 'threejs-atmosphere-aerial-perspective', relation: '主机制', role: '尘埃天空、远景衰减与大气光晕' },
      { id: 'threejs-procedural-geometry', relation: '辅助能力', role: '探测车层级部件和轮组结构' },
      { id: 'threejs-camera-direction', relation: '辅助能力', role: '轨道远景到地表任务视角' },
    ],
  },
  {
    id: 'rural-seasons', group: 'product', number: '07', title: '乡村四季数字沙盘', href: './applications.html?application=rural-seasons',
    status: '产品场景原型', summary: '用地形、农田、道路、村屋、植被、季节、天气和太阳位置构成乡村规划空间。',
    truth: '这是多种图形能力的产品组合，没有直接加载某个现成乡村 Skill。',
    boundary: '农业数据、地块边界和真实规划规则需要产品数据接入，不属于该 Skill 仓库。',
    skills: [
      { id: 'threejs-procedural-fields', relation: '基础能力', role: '地形高度、坡度和区域遮罩' },
      { id: 'threejs-procedural-vegetation', relation: '场景能力', role: '树木、作物和植被分布' },
      { id: 'threejs-procedural-architecture', relation: '场景能力', role: '村屋、仓库和聚落体块' },
      { id: 'threejs-camera-direction', relation: '观察能力', role: '总览、村口和农田镜头' },
      { id: 'threejs-atmosphere-aerial-perspective', relation: '环境能力', role: '天气、雾和远近层次' },
    ],
  },
  {
    id: 'rural-storm', group: 'product', number: '08', title: '暴雨乡村巡检', href: './applications.html?application=rural-storm',
    status: '产品场景原型', summary: '在乡村底座上叠加暴雨、积水、湿路、设施、任务点和巡检路线。',
    truth: 'Skill 提供降水、建筑和观察方法；巡检任务、风险规则和路线图由产品层实现。',
    boundary: '应急预案、设施状态和真实积水数据不是图形 Skill 的能力。',
    skills: [
      { id: 'threejs-precipitation-surfaces', relation: '主能力', role: '暴雨、湿地面、积水和天气包络' },
      { id: 'threejs-procedural-architecture', relation: '场景能力', role: '村屋、桥梁和设施空间' },
      { id: 'threejs-procedural-fields', relation: '基础能力', role: '低洼区、坡度和风险区域' },
      { id: 'threejs-camera-direction', relation: '观察能力', role: '巡检总览和设施视角' },
    ],
  },
  {
    id: 'rural-game', group: 'product', number: '09', title: '夜雨乡村游戏关卡', href: './applications.html?application=rural-game',
    status: '可玩产品原型', summary: '玩家在夜雨中移动、避开积水、调查设施、收集物资并返回安全点。',
    truth: '原仓库 Skill 负责场景图形方向；移动、碰撞、任务、风险和完成条件来自独立游戏代码。',
    boundary: '这个 24 Skill 仓库不是游戏引擎，也不提供任务系统、碰撞系统或存档系统。',
    skills: [
      { id: 'threejs-precipitation-surfaces', relation: '环境能力', role: '夜雨、湿地和积水危险区外观' },
      { id: 'threejs-procedural-architecture', relation: '关卡场景', role: '村屋与道路空间边界' },
      { id: 'threejs-camera-direction', relation: '游戏视角', role: '跟随镜头、可见区域与观察方向' },
      { id: 'threejs-visual-validation', relation: '验收方法', role: '固定路线、状态和回归证据' },
    ],
  },
  {
    id: 'park-twin', group: 'product', number: '10', title: '小区 / 园区数字孪生', href: './applications.html?application=park-twin',
    status: '产品场景原型', summary: '组合建筑、道路、绿化、天气、运营图层和摄像头视角，形成空间导览底座。',
    truth: '现阶段是程序化空间原型；Skill 提供图形生成和观看能力，没有接入真实运营数据。',
    boundary: 'GIS、BIM、摄像头视频、告警和物业数据需要外部系统。',
    skills: [
      { id: 'threejs-procedural-architecture', relation: '主能力', role: '园区建筑和体块组织' },
      { id: 'threejs-procedural-vegetation', relation: '场景能力', role: '绿地、树木和景观层' },
      { id: 'threejs-camera-direction', relation: '运营视角', role: '总览、入口、中庭和摄像头路线' },
      { id: 'threejs-shadow-systems', relation: '可增强', role: '大范围园区稳定阴影' },
    ],
  },
  {
    id: 'camping-route', group: 'product', number: '11', title: '露营 / 出行预演', href: './applications.html?application=camping-route',
    status: '生活场景原型', summary: '把地形、天气、太阳、路线、帐篷和营地布置放在同一个出行决策空间。',
    truth: 'Skill 提供地形、植被、天气和镜头方法；路线适宜性目前是演示规则。',
    boundary: '真实天气预报、地图导航和营地信息需要外部数据服务。',
    skills: [
      { id: 'threejs-procedural-fields', relation: '基础能力', role: '坡度、地形和适宜区域' },
      { id: 'threejs-procedural-vegetation', relation: '环境能力', role: '树带、草地和营地周边植被' },
      { id: 'threejs-atmosphere-aerial-perspective', relation: '天气能力', role: '雾、能见度和太阳方向' },
      { id: 'threejs-camera-direction', relation: '路线观察', role: '总览、路径和营地镜头' },
    ],
  },
  {
    id: 'night-story', group: 'product', number: '12', title: '夜间乡村故事', href: './applications.html?application=night-story',
    status: '互动叙事原型', summary: '用月光、灯笼、萤火虫、薄雾、村屋和故事路径构成夜间叙事空间。',
    truth: 'Skill 提供 VFX、镜头、大气和输出方法；故事节点与叙事内容由产品层编排。',
    boundary: '角色、对白、剧情分支和事件系统不属于图形 Skill。',
    skills: [
      { id: 'threejs-procedural-vfx', relation: '环境特效', role: '萤火虫、微粒和发光事件' },
      { id: 'threejs-camera-direction', relation: '叙事镜头', role: '路径构图和故事节点转场' },
      { id: 'threejs-atmosphere-aerial-perspective', relation: '环境层次', role: '月光薄雾和远景消失' },
      { id: 'threejs-exposure-color-grading', relation: '输出能力', role: '夜色、灯光和暗部可读性' },
    ],
  },
];

export const skillById = Object.fromEntries(THREEJS_SKILLS.map((skill) => [skill.id, skill]));
export const categoryById = Object.fromEntries(SKILL_CATEGORIES.map((category) => [category.id, category]));
